version: '0.1'
name: erfpacht058

services:
    backend:
        container_name: Erfpacht058-API
        user: "1654:1654"
        build:
            context: ./Erfpacht058-API
            dockerfile: ./Erfpacht058-API/Dockerfile
        volumes:
            - ./config/appsettings.json:/app/appsettings.json
            - ${CERTIFICATE_PATH}:/app/certificates/certificate.pfx
            - storage:/mnt/fileshare
        ports:
            - "8001:443"
        environment:
            - ASPNETCORE_Kestrel__Certificates__Default__Path=certificates/certificate.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
            - ASPNETCORE_URLS=https://+;http://+
            - e ASPNETCORE_HTTPS_PORTS=443
        privileged: true
            
    frontend:
        container_name: Erfpacht058-GUI
        build:
            context: .
            args:
                - CERTFILE=${CERTIFICATE_PATH}
                - CERTPASSWORD=${CERTIFICATE_PASSWORD}
            dockerfile: Erfpacht058-Web/Dockerfile
        volumes:
            - ./config/environment.ts:/usr/local/apache2/htdocs/assets/environment.ts
            - ./config/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
        ports:
            - "8080:443"
            
volumes:
    storage:
        driver: local
        driver_opts:
            type: cifs
            device: ${FILESHARE_PATH}
            o: username=${FILESHARE_USERNAME},password=${FILESHARE_PASSWORD}{% if FILESHARE_DOMAIN},domain=${FILESHARE_DOMAIN}{% endif %},uid=1654,gid=1654,file_mode=0777,dir_mode=0777,vers=3.0